# Generated by Django 5.1 on 2024-08-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photographic",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("awers", models.BinaryField(verbose_name="Awers")),
                ("rewers", models.BinaryField(verbose_name="Rewers")),
                ("colorized", models.BinaryField(verbose_name="Colorized Foto")),
                ("width", models.IntegerField(verbose_name="Width")),
                ("height", models.IntegerField(verbose_name="Height")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
            ],
            options={
                "verbose_name": "Photographic",
                "verbose_name_plural": "Photographics",
            },
        ),
    ]
