# Generated by Django 5.1 on 2024-08-26 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_gallery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("keyword", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.AddField(
            model_name="photographic",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="photographics", to="photo_gallery.tag"
            ),
        ),
    ]
