# Generated by Django 5.1 on 2024-09-08 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0002_faceencoding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceencoding',
            name='file',
            field=models.BinaryField(),
        ),
    ]
