# Generated by Django 5.1 on 2024-08-27 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_gallery", "0003_person_learningphotoface"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoVersion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("file", models.BinaryField(verbose_name="Photo File")),
                ("format", models.CharField(max_length=10, verbose_name="File Format")),
                (
                    "size",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="File Size"
                    ),
                ),
                (
                    "photographic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="photo_gallery.photographic",
                    ),
                ),
            ],
            options={
                "verbose_name": "Photo Version",
                "verbose_name_plural": "Photo Versions",
            },
        ),
    ]
