# Generated by Django 5.1 on 2024-09-08 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0003_alter_faceencoding_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningphotoface',
            name='personid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_photos', to='photo_gallery.person'),
        ),
    ]
