# Generated by Django 5.1 on 2024-09-16 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo_gallery', '0004_alter_learningphotoface_personid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photographic',
            name='rewers',
            field=models.BinaryField(blank=True, null=True, verbose_name='Rewers'),
        ),
    ]
